In [9]:
import ObjectiveFunctions as of
import numpy as np

x=np.array([1.2181048,9,35])
of.MI_Spring_Obj(x)[0]


227226903321.75583

In [1]:
import numpy as np
import ObjectiveFunctions as of
import GnoweeUtilities as util
import Gnowee

opt_funct=of.MI_Spring_Obj
opt_params=of.Get_Params(opt_funct,'Gnowee',dimension=3)

S=util.Settings(optimal_fitness=opt_params.o)
S.s='nolh-cdr'
S.p=25
S.a=0.5
S.fd=0.2
S.fe=0.1
S.fl=0.2
S.s='lhc'
S.sl=40
S.sf=10
S.em=200000
(timeline)=Gnowee.main(opt_funct,opt_params.lb,opt_params.ub,opt_params.vt,S,discreteVals=opt_params.dv)

print
print timeline[-1].f
print timeline[-1].e
print timeline[-1].d
print
print of.MI_Spring_Obj(timeline[-1].d)

Fitness Convergence
[[  1.20765103   9.          35.        ]
 [  1.65111669   5.          36.        ]
 [  1.6506413    5.          36.        ]
 [  1.65059476   5.          36.        ]
 [  1.64666268   5.          36.        ]
 [  1.66190089   5.          36.        ]
 [  1.66379604   5.          36.        ]
 [  1.17534653  10.          35.        ]
 [  1.17372993  10.          35.        ]
 [  1.17881943  10.          35.        ]
 [  1.60761094   5.          36.        ]
 [  1.56589151   6.          36.        ]
 [  2.19385264   3.          37.        ]
 [  2.13393636   3.          37.        ]
 [  1.47770164   7.          36.        ]
 [  1.96685312   4.          37.        ]
 [  1.97117208   4.          37.        ]
 [  1.40839502   8.          36.        ]
 [  1.82546211   5.          37.        ]
 [  1.42018619   9.          36.        ]
 [  2.4382773    3.          38.        ]
 [  1.86280826   6.0432866   37.47618692]
 [  1.49493969   9.          37.        ]
 [  1.51141081

In [5]:
print of.MI_Spring_Obj(np.array([1.2076510330422581, 9.0, 35]))

(2171219524948.0283, [-2618.4169953655219, -9.0122019238442483, -0.08299999999999996, -1.7923489669577419, -1.2673181379585099, -5.4842555771532746, -8.8817841970012523e-16, 0.046596346690973567])


In [50]:
import pyKriging  
from pyKriging.krige import kriging  
from pyKriging.samplingplan import samplingplan
import numpy as np
import ObjectiveFunctions as of
import GnoweeUtilities as util

opt_funct=of.MI_Spring_Obj
opt_params=of.Get_Params(opt_funct,'Gnowee',dimension=6)
opt_params.lb.append(0)
opt_params.ub.append(41)

# The Kriging model starts by defining a sampling plan, we use an optimal Latin Hypercube here
sp = samplingplan(2)  
X = sp.optimallhc(20)
X1=np.array([[  1.22989779,   9.,          35.93307958],
 [  1.97495591,   4.,          37.        ],
 [  1.97495612,   4.,          37.        ],
 [  1.97497135,   4.,          37.        ],
 [  1.97497227,   4.,          37.        ],
 [  1.97497557,   4.,          37.        ],
 [  1.97498173,   4.,          37.        ],
 [  1.97505063,   4.,          37.        ],
 [  1.9750696,    4.,          37.        ],
 [  1.97855739,   4.,          37.        ],
 [  1.98268578,   4.,          37.        ],
 [  1.98646116,   4.,          37.        ],
 [  2.00386279,   4.,          37.        ],
 [  2.02884805,   4.,          37.        ],
 [  2.03506503,   4.,          37.        ],
 [  1.83352703,   5.,          37.        ],
 [  1.83408116,   5.,          37.        ],
 [  1.94437431,   5.,          37.        ],
 [  1.94752622,   5.,          37.        ],
 [  2.322291,     8.76262526,  39.        ],
 [  1.22150502,   8.24505967,  39.91483704],
 [  0.37771301,   5.83021997,  34.79128737],
 [  0.14741857,   8.75251546,  27.47298103],
 [  0.11040168,   2.,          27.31492518],
 [  0.07408576,   5.01380742,  28.08592449]])
#print X

# Next, we define the problem we would like to solve
testfun = pyKriging.testfunctions().branin  
y = testfun(X)
y1=np.array([  2.67346394e+00,   3.20335003e+00,   3.20335038e+00,   3.20337508e+00,
   3.20337657e+00,   3.20338192e+00,   3.20339191e+00,   3.20350367e+00,
   3.20353444e+00,   3.20919157e+00,   3.21588776e+00,   3.22201138e+00,
   3.25023658e+00,   3.29076230e+00,   3.30084616e+00,   3.46961350e+00,
   3.47066208e+00,   3.67937163e+00,   3.68533604e+00,   9.57341875e+00,
   8.95562988e+19,   3.92914070e+20,   5.51059403e+20,   6.63909119e+20,
   8.02556664e+20])
#print y

# Now that we have our initial data, we can create an instance of a Kriging model
k = kriging(X, y, testfunction=testfun, name='simple')  
#k = kriging(X, y) 

k.train()

# Now, five infill points are added. Note that the model is re-trained after each point is added
numiter = 0  
for i in range(numiter):  
    print 'Infill iteration {0} of {1}....'.format(i + 1, numiter)
    newpoints = k.infill(1,'ei')
    print newpoints
    
    for point in newpoints:
        point[1]=round(point[1])
        point[2]=round(point[2])
        print len(point),len(opt_params.lb)
        point=util.Simple_Bounds(point,opt_params.lb,opt_params.ub)
        print point
        print "Before: ",k.predict(point), opt_funct(point)[0]
        k.addPoint(point, opt_funct(point)[0])
        print "After: ",k.predict(point), opt_funct(point)[0]
        
    newpoints = k.infill(1,'error')
    print newpoints
    
    for point in newpoints:
        point[1]=round(point[1])
        point[2]=round(point[2])
        point=util.Simple_Bounds(point,opt_params.lb,opt_params.ub)
        print point
        print "Before: ",k.predict(point), opt_funct(point)[0]
        k.addPoint(point, opt_funct(point)[0])
        print "After: ",k.predict(point), opt_funct(point)[0]
    k.train()

# And plot the results
k.plot()  

In [26]:
print X
print y
print X[11], y[11]

[[ 0.475  0.025]
 [ 0.425  0.425]
 [ 0.625  0.925]
 [ 0.025  0.825]
 [ 0.725  0.075]
 [ 0.375  0.775]
 [ 0.225  0.975]
 [ 0.975  0.875]
 [ 0.875  0.575]
 [ 0.775  0.725]
 [ 0.125  0.175]
 [ 0.575  0.225]
 [ 0.675  0.475]
 [ 0.275  0.625]
 [ 0.525  0.675]
 [ 0.825  0.325]
 [ 0.075  0.525]
 [ 0.925  0.125]
 [ 0.325  0.275]
 [ 0.175  0.375]]
[  15.30973844   19.37148401  162.8485081    23.34385067   22.43849989
   62.81707961   43.06748015  115.20981522   61.19918607  117.96512116
   93.37937367    6.46636718   51.90083418   21.07744866   61.62346487
   31.41157515   42.07993633    6.4685785    25.46181277   27.80846402]
[ 0.575  0.225] 6.46636718467


In [54]:
from scipy.optimize import minimize

def funct(x):
    v=k.predict(x)
    return v

minRes=minimize(funct,X[11])
print minRes
print minRes.x
print k.predict(minRes.x),funct(minRes.x)

minRes=minimize(funct,minRes.x)
print minRes
print minRes.x
print k.predict(minRes.x)



   status: 0
  success: True
     njev: 24
     nfev: 96
 hess_inv: array([[  3.60034190e-04,   2.70197575e-05],
       [  2.70197575e-05,   5.77275020e-05]])
      fun: 1.8079750033500854
        x: array([ 0.52647078,  0.179784  ])
  message: 'Optimization terminated successfully.'
      jac: array([ 0.,  0.])
      nit: 12
[ 0.52647078  0.179784  ]
1.80797500335 1.80797500335
   status: 0
  success: True
     njev: 1
     nfev: 4
 hess_inv: array([[1, 0],
       [0, 1]])
      fun: 1.8079750033500854
        x: array([ 0.52647078,  0.179784  ])
  message: 'Optimization terminated successfully.'
      jac: array([ 0.,  0.])
      nit: 0
[ 0.52647078  0.179784  ]
1.80797500335


In [57]:
from scipy.optimize import minimize

def efunct(x):
    v=1-k.predict_var(x)
    return v

minRes=minimize(efunct,X[11],bounds=((0,1),(0,1)))
print minRes
print minRes.x
print 1-k.predict_var(minRes.x), efunct(minRes.x)

print efunct(np.array([0,0]))

   status: 0
  success: True
     nfev: 6
 hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>
      fun: 0.93507887668493772
        x: array([ 1.,  0.])
  message: 'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
      jac: array([-0.88649384,  0.08833808])
      nit: 1
[ 1.  0.]
0.935078876685 0.935078876685
0.91408479876


In [17]:
import pyKriging  
from pyKriging.krige import kriging  
from pyKriging.samplingplan import samplingplan
import numpy as np
import ObjectiveFunctions as of
import GnoweeUtilities as util
from scipy.optimize import minimize
import SamplingMethods as sm

opt_funct=of.MI_Spring_Obj
opt_params=of.Get_Params(opt_funct,'Gnowee',dimension=6)
opt_params.lb.append(0)
opt_params.ub.append(41)

# The Kriging model starts by defining a sampling plan, we use an optimal Latin Hypercube here 
X=np.array([[  1.22989779,   9.,          35.93307958],
 [  1.97495591,   4.,          37.        ],
 [  1.97495612,   4.,          37.        ],
 [  1.97497135,   4.,          37.        ],
 [  1.97497227,   4.,          37.        ],
 [  1.97497557,   4.,          37.        ],
 [  1.97498173,   4.,          37.        ],
 [  1.97505063,   4.,          37.        ],
 [  1.9750696,    4.,          37.        ],
 [  1.97855739,   4.,          37.        ],
 [  1.98268578,   4.,          37.        ],
 [  1.98646116,   4.,          37.        ],
 [  2.00386279,   4.,          37.        ],
 [  2.02884805,   4.,          37.        ],
 [  2.03506503,   4.,          37.        ],
 [  1.83352703,   5.,          37.        ],
 [  1.83408116,   5.,          37.        ],
 [  1.94437431,   5.,          37.        ],
 [  1.94752622,   5.,          37.        ],
 [  2.322291,     8.76262526,  39.        ],
 [  1.22150502,   8.24505967,  39.91483704],
 [  0.37771301,   5.83021997,  34.79128737],
 [  0.14741857,   8.75251546,  27.47298103],
 [  0.11040168,   2.,          27.31492518],
 [  0.07408576,   5.01380742,  28.08592449]])
#print X

# Next, we define the problem we would like to solve
Y=np.array([  2.67346394e+00,   3.20335003e+00,   3.20335038e+00,   3.20337508e+00,
   3.20337657e+00,   3.20338192e+00,   3.20339191e+00,   3.20350367e+00,
   3.20353444e+00,   3.20919157e+00,   3.21588776e+00,   3.22201138e+00,
   3.25023658e+00,   3.29076230e+00,   3.30084616e+00,   3.46961350e+00,
   3.47066208e+00,   3.67937163e+00,   3.68533604e+00,   9.57341875e+00,
   8.95562988e+19,   3.92914070e+20,   5.51059403e+20,   6.63909119e+20,
   8.02556664e+20])
#print y

init=sm.Initial_Samples(np.array(opt_params.lb),np.array(opt_params.ub),'lhc',25)
init[:,1:]=np.rint(init[:,1:])
initY=[]
for i in init:
    initY.append(opt_funct(i)[0])
X=np.concatenate((X,init),axis=0)
Y=np.concatenate((Y,initY),axis=0)
print X
print Y

# Now that we have our initial data, we can create an instance of a Kriging model
k = kriging(X, Y) 

k.train()

n=0
for i in range(n):
    # Choose point based on current best location
    def funct(x):
        x[1]=round(x[1])
        x[2]=round(x[2])
        v=k.predict(x)
        return v

    print "Iter #{}, best point method:".format(n)
    print X[1]
    print opt_funct(X[1])[0]

    minVal=minimize(funct,X[1],bounds=((0,3),(1,10),(0,41)))
    k.addPoint(minVal.x,opt_funct(minVal.x)[0])
    print minVal
    print minVal.x
    print k.predict(minVal.x),opt_funct(minVal.x)[0]
    print
    
    # Choose point based on variance of model
    print "Iter #{}, variance reduction method:".format(n)
    x_var=k.infill(1,'error')[0]
    print x_var

    def efunct(x):
        x[1]=round(x[1])
        x[2]=round(x[2])
        v=1-k.predict_var(x)
        return v

    minErr=minimize(efunct,x_var,bounds=((0.01,3),(1,10),(0,41)))
    k.addPoint(minErr.x,opt_funct(minErr.x)[0])
    print minErr
    print minErr.x
    print 1-k.predict_var(minErr.x)
    print 
    
    k.train()

[[  1.22989779   9.          35.93307958]
 [  1.97495591   4.          37.        ]
 [  1.97495612   4.          37.        ]
 [  1.97497135   4.          37.        ]
 [  1.97497227   4.          37.        ]
 [  1.97497557   4.          37.        ]
 [  1.97498173   4.          37.        ]
 [  1.97505063   4.          37.        ]
 [  1.9750696    4.          37.        ]
 [  1.97855739   4.          37.        ]
 [  1.98268578   4.          37.        ]
 [  1.98646116   4.          37.        ]
 [  2.00386279   4.          37.        ]
 [  2.02884805   4.          37.        ]
 [  2.03506503   4.          37.        ]
 [  1.83352703   5.          37.        ]
 [  1.83408116   5.          37.        ]
 [  1.94437431   5.          37.        ]
 [  1.94752622   5.          37.        ]
 [  2.322291     8.76262526  39.        ]
 [  1.22150502   8.24505967  39.91483704]
 [  0.37771301   5.83021997  34.79128737]
 [  0.14741857   8.75251546  27.47298103]
 [  0.11040168   2.          27.31

In [18]:
# Choose point based on current best location
def funct(x):
    x[1]=round(x[1])
    x[2]=round(x[2])
    v=k.predict(x)
    return v

print "Iter #{}, best point method:".format(n)
print X[1]
print k.predict(X[1]),opt_funct(X[1])[0]

minVal=minimize(funct,X[1],bounds=((0.01,3),(1,10),(0,41)))
k.addPoint(minVal.x,opt_funct(minVal.x)[0])
print minVal
print minVal.x
print k.predict(minVal.x),opt_funct(minVal.x)[0]
print


Iter #0, best point method:
[  1.97495591   4.          37.        ]
-1.69436709363e+29 3.20335003025
   status: 2
  success: False
     nfev: 84
 hess_inv: <3x3 LbfgsInvHessProduct with dtype=float64>
      fun: -1.6943670936284649e+29
        x: array([  1.97495591,   4.        ,  37.        ])
  message: 'ABNORMAL_TERMINATION_IN_LNSRCH'
      jac: array([  8.90020253e+35,   0.00000000e+00,   0.00000000e+00])
      nit: 0
[  1.97495591   4.          37.        ]
2.05058705272e+28 3.20335003025



In [3]:
import pyKriging  
from pyKriging.krige import kriging  
from pyKriging.samplingplan import samplingplan
import numpy as np
import ObjectiveFunctions as of
import GnoweeUtilities as util
from scipy.optimize import minimize
import SamplingMethods as sm

opt_funct=of.Spring_Obj
opt_params=of.Get_Params(opt_funct,'Gnowee',dimension=3)

# The Kriging model starts by defining a sampling plan, we use an optimal Latin Hypercube here 
xOut=np.array([[  0.0501909,    0.32123686,  13.80346665],
 [  0.05193759,   0.35987732,  11.21194855],
 [  0.05047078,   0.32618961,  13.52238681],
 [  0.05155328,   0.35143536,  11.83943881],
 [  0.05,         0.31378522,  14.56518177],
 [  0.05002886,   0.31364893,  14.58370358],
 [  0.0547937,    0.43460327,   8.00007585],
 [  0.05032471,   0.3207653 ,  14.18483223],
 [  0.05011247,   0.31789771,  14.50714541],
 [  0.05458181,   0.42738777,   8.49534384],
 [  0.05570803,   0.45234829,   7.59743872],
 [  0.05570803,   0.45234829,   7.59743872],
 [  0.0572067 ,   0.50042069,   6.29375968],
 [  0.05108934,   0.32846657,  13.99241058],
 [  0.05278429,   0.37744258,  11.12826427],
 [  0.05104608,   0.33788833,  13.71959408],
 [  0.05385014,   0.38688463,  10.43134295],
 [  0.05152156,   0.33619841,  13.71061663],
 [  0.05192719,   0.33867099,  13.48449431],
 [  0.05999931,   0.57635593,   4.90038847],
 [  0.06015361,   0.58058734,   4.89100305],
 [  0.05662418,   0.45075934,   8.11667537],
 [  0.0637329 ,   0.69904064,   3.47029334],])
yOut=np.array([  1.27887395e-02,   1.28258137e-02,   1.28975945e-02,   1.29263701e-02,
   1.29947729e-02,   1.30186680e-02,   1.30484065e-02,   1.31479523e-02,
   1.31780457e-02,   1.33633270e-02,   1.34729879e-02,   1.34729879e-02,
   1.35825235e-02,   1.37108913e-02,   1.38059894e-02,   1.38401047e-02,
   1.39467568e-02,   1.40206102e-02,   1.41404954e-02,   1.43171577e-02,
   1.44768264e-02,   1.46213161e-02,   1.55324642e-02])
X=sm.Initial_Samples(np.array(opt_params.lb),np.array(opt_params.ub),'lhc',125)
Y=[]
#for i in X:
#    Y.append(opt_funct(i,1)[0])
#X=np.concatenate((X,xOut),axis=0)
#Y=np.concatenate((Y,yOut),axis=0)
X=xOut
Y=yOut
print X
print Y

# Now that we have our initial data, we can create an instance of a Kriging model
k = kriging(X, Y) 

k.train()

# Choose point based on current best location
def funct(x):
    v=k.predict(x)
    return v
def efunct(x):
    v=1-k.predict_var(x)
    return v

n=0
for i in range(n):

    print "Iter #{}, best point method:".format(n)
    print X[1]
    print opt_funct(X[1])[0]

    minVal=minimize(funct,X[1],bounds=((0,3),(1,10),(0,41)))
    k.addPoint(minVal.x,opt_funct(minVal.x)[0])
    print minVal
    print minVal.x
    print k.predict(minVal.x),opt_funct(minVal.x)[0]
    print
    
    # Choose point based on variance of model
    print "Iter #{}, variance reduction method:".format(n)
    x_var=k.infill(1,'error')[0]
    print x_var


    minErr=minimize(efunct,x_var,bounds=((0.01,3),(1,10),(0,41)))
    k.addPoint(minErr.x,opt_funct(minErr.x)[0])
    print minErr
    print minErr.x
    print 1-k.predict_var(minErr.x)
    print 
    
    k.train()

[[  0.0501909    0.32123686  13.80346665]
 [  0.05193759   0.35987732  11.21194855]
 [  0.05047078   0.32618961  13.52238681]
 [  0.05155328   0.35143536  11.83943881]
 [  0.05         0.31378522  14.56518177]
 [  0.05002886   0.31364893  14.58370358]
 [  0.0547937    0.43460327   8.00007585]
 [  0.05032471   0.3207653   14.18483223]
 [  0.05011247   0.31789771  14.50714541]
 [  0.05458181   0.42738777   8.49534384]
 [  0.05570803   0.45234829   7.59743872]
 [  0.05570803   0.45234829   7.59743872]
 [  0.0572067    0.50042069   6.29375968]
 [  0.05108934   0.32846657  13.99241058]
 [  0.05278429   0.37744258  11.12826427]
 [  0.05104608   0.33788833  13.71959408]
 [  0.05385014   0.38688463  10.43134295]
 [  0.05152156   0.33619841  13.71061663]
 [  0.05192719   0.33867099  13.48449431]
 [  0.05999931   0.57635593   4.90038847]
 [  0.06015361   0.58058734   4.89100305]
 [  0.05662418   0.45075934   8.11667537]
 [  0.0637329    0.69904064   3.47029334]]
[ 0.01278874  0.01282581  0.01289

In [5]:
# Choose point based on current best location
def funct(x):
    v=k.predict(x)
    return v

print "Iter #{}, best point method:".format(n)
print X[0]
print k.predict(X[0]),opt_funct(X[0],1)[0]

minVal=minimize(funct,X[0],bounds=((0.05,2.0),(0.25,1.3),(2.0,15.0)))
k.addPoint(minVal.x,opt_funct(minVal.x,1)[0])
print minVal
print minVal.x
print k.predict(minVal.x),opt_funct(minVal.x,1)[0]
print

test=sm.Initial_Samples(np.array(opt_params.lb),np.array(opt_params.ub),'random',1)
print test
print k.predict(test[0]),opt_funct(test[0],1)[0]
print

optim=np.array([0.05169046,0.356750, 11.287126]) 
print k.predict(optim),opt_funct(optim,1)[0]

Iter #0, best point method:
[  0.0501909    0.32123686  13.80346665]
0.0127887394869 0.0127887383801
   status: 0
  success: True
     nfev: 84
 hess_inv: <3x3 LbfgsInvHessProduct with dtype=float64>
      fun: 0.0098481711154389858
        x: array([  0.05      ,   0.25      ,  13.78919375])
  message: 'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
      jac: array([ 0.38219344,  0.04463178, -0.00604936])
      nit: 4
[  0.05         0.25        13.78919375]
1.00986691394 1.00986824609

[[ 1.00867455  1.02638265  5.13798718]]
0.0021429123955 9.45396230822

0.0117467913971 0.0126653101469
